// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class FirebaseConfig {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0dJeguIXS-a3AJFbcYZdBLLlg64Zsnw',
    appId: '1:312961060294:web:0d39b042b59f59b1b736c7',
    messagingSenderId: '312961060294',
    projectId: 'appfirebase-f2358',
    authDomain: 'appfirebase-f2358.firebaseapp.com',
    storageBucket: 'appfirebase-f2358.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF0dJeguIXS-a3AJFbcYZdBLLlg64Zsnw',
    appId: '1:312961060294:web:0d39b042b59f59b1b736c7',
    messagingSenderId: '312961060294',
    projectId: 'appfirebase-f2358',
    storageBucket: 'appfirebase-f2358.appspot.com',
  );
}
